// ============================================================
// Types
// ============================================================

export interface Wine {
  slug: string;
  name: string;
  region_zh: string;
  region_en: string;
  tags_zh: string[];
  tags_en: string[];
  description_zh: string;
  description_en: string;
  minPrice: number;
  merchantCount: number;
  emoji: string;
  badge?: string;
  type: "red" | "white" | "sparkling" | "rosé" | "dessert";
  grape_variety?: string;
  vintage?: number;
  is_featured?: boolean;
  tasting_notes?: {
    appearance_zh?: string;
    appearance_en?: string;
    nose_zh?: string;
    nose_en?: string;
    palate_zh?: string;
    palate_en?: string;
    food_zh?: string[];
    food_en?: string[];
  };
  region_story_zh?: string;
  region_story_en?: string;
}

export interface MerchantPrice {
  merchant: string;
  merchantSlug: string;
  price: number;
  isBest: boolean;
}

export interface Merchant {
  slug: string;
  name: string;
  description_zh: string;
  description_en: string;
  details_zh: string[];
  details_en: string[];
  winesListed: number;
  bestPrices: number;
  rating: number;
}

export interface Scene {
  slug: string;
  title_zh: string;
  title_en: string;
  description_zh: string;
  description_en: string;
  emoji: string;
  wineSlugs: string[];
}

export interface Tag {
  slug: string;
  name_zh: string;
  name_en: string;
}

// ============================================================
// Merchants (6)
// ============================================================

export const merchants: Merchant[] = [
  {
    slug: "watsons-wine",
    name: "Watson's Wine",
    description_zh: "深耕香港葡萄酒市場超過二十年，Watson's Wine 擁有全港最齊全的葡萄酒庫存之一。從日常餐酒到珍藏年份，為每位愛酒人提供可靠的選擇。",
    description_en: "With over twenty years in the Hong Kong wine market, Watson's Wine offers one of the city's most comprehensive wine selections.",
    details_zh: ["📍 全港多間門店", "🚚 次日送達", "💳 支持多種付款方式"],
    details_en: ["📍 Multiple locations", "🚚 Next-day delivery", "💳 Multiple payment options"],
    winesListed: 126,
    bestPrices: 23,
    rating: 4.6,
  },
  {
    slug: "wine-and-co",
    name: "Wine & Co",
    description_zh: "專注歐洲精品酒莊的進口商，主打法國、意大利小農酒。每支酒都有故事，每個年份都值得細品。",
    description_en: "A boutique importer focused on European artisan wineries — mainly French and Italian small producers.",
    details_zh: ["📍 中環門店", "🚚 港島即日送", "💳 Wine Club 會員折扣"],
    details_en: ["📍 Central shop", "🚚 Same-day HK Island", "💳 Wine Club discounts"],
    winesListed: 89,
    bestPrices: 15,
    rating: 4.7,
  },
  {
    slug: "cellardoor",
    name: "CellarDoor",
    description_zh: "新世代線上酒舖，以年輕化選酒和親民定價著稱。網站介面清爽，下單方便，經常有限時優惠。",
    description_en: "A new-generation online wine shop known for approachable selections and fair pricing.",
    details_zh: ["📍 純線上", "🚚 免費送貨滿$500", "💳 信用卡/FPS"],
    details_en: ["📍 Online only", "🚚 Free delivery over $500", "💳 Credit card / FPS"],
    winesListed: 74,
    bestPrices: 18,
    rating: 4.4,
  },
  {
    slug: "vinhk",
    name: "VinHK",
    description_zh: "主打自然酒和有機酒的專門店，為注重健康和風土的飲家提供獨特選擇。",
    description_en: "Specializing in natural and organic wines for health-conscious drinkers who care about terroir.",
    details_zh: ["📍 西營盤門店", "🚚 預約送貨", "💳 現金/轉數快"],
    details_en: ["📍 Sai Ying Pun shop", "🚚 Scheduled delivery", "💳 Cash / FPS"],
    winesListed: 62,
    bestPrices: 10,
    rating: 4.5,
  },
  {
    slug: "grape-hk",
    name: "Grape HK",
    description_zh: "以批量採購壓低成本，提供極具競爭力的價格。適合想囤貨或團購的消費者。",
    description_en: "Leverages bulk purchasing for competitive pricing. Great for stocking up or group buys.",
    details_zh: ["📍 觀塘倉庫自取", "🚚 購滿12支免運", "💳 銀行轉帳優惠"],
    details_en: ["📍 Kwun Tong warehouse pickup", "🚚 Free shipping 12+ bottles", "💳 Bank transfer discount"],
    winesListed: 95,
    bestPrices: 28,
    rating: 4.3,
  },
  {
    slug: "bottleshop",
    name: "BottleShop",
    description_zh: "精選世界各地得獎酒款，每月推出主題酒單。適合想嘗鮮又不想踩雷的飲家。",
    description_en: "Curated award-winning wines from around the world with monthly themed selections.",
    details_zh: ["📍 銅鑼灣門店", "🚚 標準配送", "💳 多種付款"],
    details_en: ["📍 Causeway Bay shop", "🚚 Standard delivery", "💳 Multiple payment options"],
    winesListed: 83,
    bestPrices: 12,
    rating: 4.5,
  },
];

export const partners = merchants.map((m) => m.name);

// ============================================================
// Wines (32)
// ============================================================

export const wines: Wine[] = [
  // 1
  {
    slug: "cloudy-bay-sauvignon-blanc-2023",
    name: "Cloudy Bay Sauvignon Blanc 2023",
    type: "white",
    region_zh: "紐西蘭 · 馬爾堡羅 · 白酒",
    region_en: "New Zealand · Marlborough · White",
    grape_variety: "Sauvignon Blanc",
    vintage: 2023,
    tags_zh: ["清爽易飲", "適合配海鮮", "新手友好"],
    tags_en: ["Easy drinking", "Pairs with seafood", "Beginner-friendly"],
    description_zh: "如果你喜歡清爽不膩的白酒，這支很難踩雷。帶點青草和柑橘香氣，配海鮮特別好。",
    description_en: "If you like crisp, refreshing whites, this one rarely disappoints. Hints of fresh grass and citrus.",
    minPrice: 138,
    merchantCount: 6,
    emoji: "🍾",
    badge: "Editor's Pick",
    is_featured: true,
    tasting_notes: {
      appearance_zh: "淺稻草色，帶綠色光澤",
      appearance_en: "Pale straw with green tints",
      nose_zh: "青草、百香果、柑橘皮、淡淡的燧石礦物味",
      nose_en: "Cut grass, passionfruit, citrus zest, flinty minerals",
      palate_zh: "入口清脆，酸度明亮，中等酒體，收尾乾淨清爽",
      palate_en: "Crisp entry, bright acidity, medium body, clean finish",
      food_zh: ["聚餐", "海鮮", "沙拉", "夏日午後", "朋友聚會"],
      food_en: ["Dinner parties", "Seafood", "Salads", "Summer afternoons"],
    },
    region_story_zh: "馬爾堡羅位於紐西蘭南島的東北端，是全球公認的長相思聖地。這裡日照充足但夜晚涼爽，葡萄可以緩慢成熟，保留住清脆的酸度和豐富的果香。Cloudy Bay 酒莊創立於 1985 年，幾乎憑一己之力讓紐西蘭長相思登上世界舞台。",
    region_story_en: "Marlborough sits at the northeastern tip of New Zealand's South Island and is globally recognized as the spiritual home of Sauvignon Blanc. Long sunshine hours paired with cool nights allow grapes to ripen slowly, preserving crisp acidity and vibrant fruit character.",
  },
  // 2
  {
    slug: "moet-chandon-brut-imperial",
    name: "Moët & Chandon Brut Impérial",
    type: "sparkling",
    region_zh: "法國 · 香檳區 · 氣泡酒",
    region_en: "France · Champagne · Sparkling",
    grape_variety: "Chardonnay / Pinot Noir / Pinot Meunier",
    tags_zh: ["送禮首選", "開瓶就有儀式感"],
    tags_en: ["Great for gifting", "Crowd-pleaser"],
    description_zh: "送香檳基本不會出錯。金色酒液、細膩氣泡，任何場合都撐得住場面。",
    description_en: "You can never go wrong with Champagne. Golden hues, fine bubbles — a gift in itself.",
    minPrice: 268,
    merchantCount: 8,
    emoji: "🥂",
    is_featured: true,
    tasting_notes: {
      appearance_zh: "金黃色，氣泡細膩持久",
      appearance_en: "Golden yellow with fine persistent bubbles",
      nose_zh: "白花、柑橘、烤杏仁",
      nose_en: "White flowers, citrus, toasted almonds",
      palate_zh: "優雅豐富，果味與礦物感平衡",
      palate_en: "Elegant and rich, balanced fruit and mineral notes",
      food_zh: ["慶祝", "開胃菜", "海鮮拼盤"],
      food_en: ["Celebrations", "Appetizers", "Seafood platters"],
    },
    region_story_zh: "香檳區位於巴黎東北方約 150 公里，是法國最北的葡萄酒產區。Moët & Chandon 創立於 1743 年，是全球最知名的香檳品牌之一。",
    region_story_en: "The Champagne region lies about 150km northeast of Paris and is France's northernmost wine region. Moët & Chandon, founded in 1743, is one of the world's most iconic Champagne houses.",
  },
  // 3
  {
    slug: "whispering-angel-rose-2023",
    name: "Whispering Angel Rosé 2023",
    type: "rosé",
    region_zh: "法國 · 普羅旺斯 · 粉紅酒",
    region_en: "France · Provence · Rosé",
    grape_variety: "Grenache / Cinsault / Rolle",
    vintage: 2023,
    tags_zh: ["夏天喝很爽", "拍照好看", "不踩雷"],
    tags_en: ["Summer favourite", "Instagram-worthy"],
    description_zh: "淡粉色的瓶身已經贏了一半。清爽的草莓和白桃香氣，冰鎮後配沙拉最棒。",
    description_en: "The pale pink bottle is half the charm. Fresh strawberry and white peach aromas — pure summer.",
    minPrice: 198,
    merchantCount: 5,
    emoji: "🍷",
    is_featured: true,
    tasting_notes: {
      appearance_zh: "淡三文魚粉色",
      appearance_en: "Pale salmon pink",
      nose_zh: "草莓、白桃、柑橘花",
      nose_en: "Strawberry, white peach, citrus blossom",
      palate_zh: "清爽圓潤，微微礦物感",
      palate_en: "Fresh and round with subtle minerality",
      food_zh: ["沙拉", "海鮮", "戶外野餐"],
      food_en: ["Salads", "Seafood", "Outdoor picnics"],
    },
    region_story_zh: "普羅旺斯是全球粉紅酒的標杆產區，地中海氣候賦予葡萄完美的成熟度和清爽的酸度。",
    region_story_en: "Provence is the benchmark region for rosé worldwide. The Mediterranean climate provides perfect grape ripeness with refreshing acidity.",
  },
  // 4
  {
    slug: "penfolds-bin-389-2021",
    name: "Penfolds Bin 389 2021",
    type: "red",
    region_zh: "澳洲 · 南澳 · 紅酒",
    region_en: "Australia · South Australia · Red",
    grape_variety: "Cabernet Sauvignon / Shiraz",
    vintage: 2021,
    tags_zh: ["適合配紅肉", "性價比高"],
    tags_en: ["Pairs with red meat", "Great value"],
    description_zh: "澳洲紅酒的經典代表，果味濃郁但不失結構，配牛排最對味。",
    description_en: "A classic Australian red — rich fruit with good structure. Perfect with steak.",
    minPrice: 328,
    merchantCount: 7,
    emoji: "🍷",
    tasting_notes: {
      appearance_zh: "深紅寶石色",
      appearance_en: "Deep ruby red",
      nose_zh: "黑醋栗、巧克力、香草",
      nose_en: "Blackcurrant, chocolate, vanilla",
      palate_zh: "飽滿濃郁，單寧成熟，餘韻悠長",
      palate_en: "Full and rich, ripe tannins, long finish",
      food_zh: ["牛排", "燒烤", "硬質芝士"],
      food_en: ["Steak", "BBQ", "Hard cheese"],
    },
    region_story_zh: "南澳是澳洲最重要的葡萄酒產區，以溫暖乾燥的氣候著稱。Penfolds 是澳洲最受尊崇的酒莊之一。",
    region_story_en: "South Australia is Australia's most important wine region, known for its warm, dry climate. Penfolds is one of Australia's most revered wineries.",
  },
  // 5
  {
    slug: "masi-costasera-amarone-2018",
    name: "Masi Costasera Amarone 2018",
    type: "red",
    region_zh: "意大利 · 威尼托 · 紅酒",
    region_en: "Italy · Veneto · Red",
    grape_variety: "Corvina / Rondinella / Molinara",
    vintage: 2018,
    tags_zh: ["果香豐富", "適合冬天"],
    tags_en: ["Rich fruit", "Winter wine"],
    description_zh: "意大利經典風乾葡萄釀造，濃郁醇厚，適合冬天慢慢品嚐。",
    description_en: "Classic Italian Amarone made from dried grapes — rich and warming, perfect for winter evenings.",
    minPrice: 388,
    merchantCount: 4,
    emoji: "🍾",
    tasting_notes: {
      appearance_zh: "深石榴紅色",
      appearance_en: "Deep garnet red",
      nose_zh: "乾果、可可、菸草、香料",
      nose_en: "Dried fruit, cocoa, tobacco, spices",
      palate_zh: "濃郁豐厚，帶甜美果味，餘韻帶杏仁苦味",
      palate_en: "Rich and velvety, sweet fruit flavors, almond-bitter finish",
      food_zh: ["燉肉", "野味", "陳年芝士"],
      food_en: ["Stewed meats", "Game", "Aged cheese"],
    },
    region_story_zh: "威尼托位於意大利東北部，Amarone 是該產區最珍貴的酒款，使用風乾數月的葡萄釀造，風味極為濃縮。",
    region_story_en: "Veneto is in northeastern Italy. Amarone is the region's most prized wine, made from grapes dried for months to concentrate their flavors.",
  },
  // 6
  {
    slug: "santa-margherita-pinot-grigio",
    name: "Santa Margherita Pinot Grigio",
    type: "white",
    region_zh: "意大利 · 特倫蒂諾 · 白酒",
    region_en: "Italy · Trentino · White",
    grape_variety: "Pinot Grigio",
    tags_zh: ["清爽易飲", "百搭"],
    tags_en: ["Easy drinking", "Versatile"],
    description_zh: "清爽百搭的意大利白酒，不管配什麼菜都不會出錯。",
    description_en: "A crisp, versatile Italian white that goes with just about anything.",
    minPrice: 168,
    merchantCount: 5,
    emoji: "🥂",
    tasting_notes: {
      appearance_zh: "淺稻草色",
      appearance_en: "Pale straw",
      nose_zh: "青蘋果、白花、礦物",
      nose_en: "Green apple, white flowers, minerals",
      palate_zh: "清脆乾爽，酸度適中",
      palate_en: "Crisp and dry, moderate acidity",
      food_zh: ["意麵", "沙拉", "白肉"],
      food_en: ["Pasta", "Salads", "White meat"],
    },
    region_story_zh: "特倫蒂諾位於意大利北部阿爾卑斯山腳，涼爽的氣候讓白葡萄保留了清新的果味和酸度。",
    region_story_en: "Trentino sits at the foot of the Alps in northern Italy. The cool climate preserves fresh fruit flavors and acidity in white grapes.",
  },
  // 7
  {
    slug: "chateau-mouton-rothschild-2018",
    name: "Château Mouton Rothschild 2018",
    type: "red",
    region_zh: "法國 · 波爾多 · 紅酒",
    region_en: "France · Bordeaux · Red",
    grape_variety: "Cabernet Sauvignon / Merlot",
    vintage: 2018,
    tags_zh: ["值得收藏", "頂級之選"],
    tags_en: ["Worth collecting", "Premium pick"],
    description_zh: "波爾多五大名莊之一，2018 年份被譽為完美年份，收藏或品飲皆宜。",
    description_en: "One of Bordeaux's First Growths — the 2018 vintage is considered near-perfect for cellaring or drinking.",
    minPrice: 4800,
    merchantCount: 3,
    emoji: "🍷",
    badge: "Collector",
    tasting_notes: {
      appearance_zh: "深紫紅色",
      appearance_en: "Deep purple-red",
      nose_zh: "黑醋栗、雪松、石墨、紫羅蘭",
      nose_en: "Blackcurrant, cedar, graphite, violets",
      palate_zh: "宏大而精細，單寧如絲般細膩",
      palate_en: "Grand yet refined, silky tannins",
      food_zh: ["羊排", "松露料理", "陳年芝士"],
      food_en: ["Lamb chops", "Truffle dishes", "Aged cheese"],
    },
  },
  // 8
  {
    slug: "opus-one-2019",
    name: "Opus One 2019",
    type: "red",
    region_zh: "美國 · 納帕谷 · 紅酒",
    region_en: "USA · Napa Valley · Red",
    grape_variety: "Cabernet Sauvignon / Merlot / Cab Franc",
    vintage: 2019,
    tags_zh: ["頂級之選", "值得收藏"],
    tags_en: ["Premium pick", "Worth collecting"],
    description_zh: "納帕谷殿堂級名莊，法美合作的結晶，優雅而不失力量。",
    description_en: "A legendary Napa Valley estate — the Franco-American collaboration that redefined California wine.",
    minPrice: 3200,
    merchantCount: 4,
    emoji: "🍷",
    badge: "Premium",
    tasting_notes: {
      appearance_zh: "深寶石紅",
      appearance_en: "Deep ruby",
      nose_zh: "黑莓、紫羅蘭、可可、月桂",
      nose_en: "Blackberry, violet, cocoa, bay laurel",
      palate_zh: "絲滑豐滿，層次複雜",
      palate_en: "Silky and full, complex layers",
      food_zh: ["牛排", "燉牛尾", "黑松露"],
      food_en: ["Steak", "Braised oxtail", "Black truffle"],
    },
  },
  // 9
  {
    slug: "louis-roederer-cristal-2015",
    name: "Louis Roederer Cristal 2015",
    type: "sparkling",
    region_zh: "法國 · 香檳區 · 氣泡酒",
    region_en: "France · Champagne · Sparkling",
    grape_variety: "Pinot Noir / Chardonnay",
    vintage: 2015,
    tags_zh: ["頂級之選", "送禮首選"],
    tags_en: ["Premium pick", "Great for gifting"],
    description_zh: "頂級年份香檳代表，為沙皇而生。極致細膩的氣泡和深邃的風味。",
    description_en: "The pinnacle of prestige Champagne, originally created for the Tsar. Exquisite bubbles and profound depth.",
    minPrice: 2800,
    merchantCount: 3,
    emoji: "🥂",
    badge: "Luxury",
    tasting_notes: {
      appearance_zh: "閃耀金黃色",
      appearance_en: "Brilliant gold",
      nose_zh: "榛子、柑橘蜜、白花、粉筆",
      nose_en: "Hazelnut, citrus honey, white flowers, chalk",
      palate_zh: "極其精緻，奶油般質地，無盡餘韻",
      palate_en: "Extremely refined, creamy texture, endless finish",
      food_zh: ["魚子醬", "龍蝦", "精緻法餐"],
      food_en: ["Caviar", "Lobster", "Fine French cuisine"],
    },
  },
  // 10
  {
    slug: "veuve-clicquot-yellow-label",
    name: "Veuve Clicquot Yellow Label",
    type: "sparkling",
    region_zh: "法國 · 香檳區 · 氣泡酒",
    region_en: "France · Champagne · Sparkling",
    grape_variety: "Pinot Noir / Chardonnay / Pinot Meunier",
    tags_zh: ["送禮首選", "適合慶祝"],
    tags_en: ["Great for gifting", "Perfect for celebrations"],
    description_zh: "黃牌香檳辨識度超高，果味豐富，慶祝場合的首選。",
    description_en: "The iconic yellow label — rich, fruit-forward Champagne that's perfect for celebrations.",
    minPrice: 328,
    merchantCount: 6,
    emoji: "🥂",
    tasting_notes: {
      appearance_zh: "金黃色",
      appearance_en: "Golden yellow",
      nose_zh: "烤面包、杏桃、香草",
      nose_en: "Toasted bread, apricot, vanilla",
      palate_zh: "豐富圓潤，氣泡活潑",
      palate_en: "Rich and round, lively bubbles",
      food_zh: ["慶祝", "開胃菜", "壽司"],
      food_en: ["Celebrations", "Appetizers", "Sushi"],
    },
  },
  // 11
  {
    slug: "dom-perignon-2013",
    name: "Dom Pérignon 2013",
    type: "sparkling",
    region_zh: "法國 · 香檳區 · 氣泡酒",
    region_en: "France · Champagne · Sparkling",
    grape_variety: "Chardonnay / Pinot Noir",
    vintage: 2013,
    tags_zh: ["頂級之選", "值得收藏"],
    tags_en: ["Premium pick", "Worth collecting"],
    description_zh: "香檳之王，每個年份都是藝術品。2013 年清新而精確，展現極致平衡。",
    description_en: "The King of Champagne — every vintage is a work of art. The 2013 is fresh, precise, and supremely balanced.",
    minPrice: 1880,
    merchantCount: 4,
    emoji: "🥂",
    badge: "Icon",
    tasting_notes: {
      appearance_zh: "明亮金黃",
      appearance_en: "Bright golden",
      nose_zh: "白花、柑橘、杏仁、輕煙燻",
      nose_en: "White flowers, citrus, almonds, light smoke",
      palate_zh: "精準有力，極致平衡",
      palate_en: "Precise and powerful, supreme balance",
      food_zh: ["精緻海鮮", "日本料理", "慶典"],
      food_en: ["Fine seafood", "Japanese cuisine", "Celebrations"],
    },
  },
  // 12
  {
    slug: "marlborough-villa-maria-sauvignon-blanc-2023",
    name: "Villa Maria Sauvignon Blanc 2023",
    type: "white",
    region_zh: "紐西蘭 · 馬爾堡羅 · 白酒",
    region_en: "New Zealand · Marlborough · White",
    grape_variety: "Sauvignon Blanc",
    vintage: 2023,
    tags_zh: ["清爽易飲", "性價比高"],
    tags_en: ["Easy drinking", "Great value"],
    description_zh: "馬爾堡羅另一經典白酒，百香果和青椒香氣特別鮮明，CP值超高。",
    description_en: "Another Marlborough classic — vibrant passionfruit and capsicum notes with excellent value.",
    minPrice: 98,
    merchantCount: 5,
    emoji: "🍾",
    badge: "Best Value",
    tasting_notes: {
      appearance_zh: "淺黃綠色",
      appearance_en: "Pale yellow-green",
      nose_zh: "百香果、青椒、葡萄柚",
      nose_en: "Passionfruit, capsicum, grapefruit",
      palate_zh: "多汁清脆，酸度活潑",
      palate_en: "Juicy and crisp, vibrant acidity",
      food_zh: ["海鮮", "亞洲菜", "沙拉"],
      food_en: ["Seafood", "Asian cuisine", "Salads"],
    },
  },
  // 13
  {
    slug: "chablis-william-fevre-2022",
    name: "William Fèvre Chablis 2022",
    type: "white",
    region_zh: "法國 · 勃艮第 · 白酒",
    region_en: "France · Burgundy · White",
    grape_variety: "Chardonnay",
    vintage: 2022,
    tags_zh: ["適合配海鮮", "新手友好"],
    tags_en: ["Pairs with seafood", "Beginner-friendly"],
    description_zh: "夏布利的礦物感白酒代表，清冽如泉水，配生蠔絕配。",
    description_en: "The quintessential mineral-driven Chablis — as clear as spring water, sublime with oysters.",
    minPrice: 228,
    merchantCount: 4,
    emoji: "🍾",
    tasting_notes: {
      appearance_zh: "淺金色",
      appearance_en: "Pale gold",
      nose_zh: "燧石、青蘋果、檸檬",
      nose_en: "Flint, green apple, lemon",
      palate_zh: "礦物感突出，酸度清冽",
      palate_en: "Pronounced minerality, bracing acidity",
      food_zh: ["生蠔", "白灼蝦", "壽司"],
      food_en: ["Oysters", "Poached prawns", "Sushi"],
    },
  },
  // 14
  {
    slug: "sancerre-pascal-jolivet-2022",
    name: "Pascal Jolivet Sancerre 2022",
    type: "white",
    region_zh: "法國 · 盧瓦爾河谷 · 白酒",
    region_en: "France · Loire Valley · White",
    grape_variety: "Sauvignon Blanc",
    vintage: 2022,
    tags_zh: ["清爽易飲", "適合配海鮮"],
    tags_en: ["Easy drinking", "Pairs with seafood"],
    description_zh: "法國長相思的正宗風味，比紐西蘭的更含蓄，帶燧石和白花香氣。",
    description_en: "The French take on Sauvignon Blanc — more restrained than New Zealand, with flint and white flower notes.",
    minPrice: 248,
    merchantCount: 3,
    emoji: "🍾",
    tasting_notes: {
      appearance_zh: "透亮銀黃色",
      appearance_en: "Bright silver-yellow",
      nose_zh: "白花、燧石、柑橘",
      nose_en: "White flowers, flint, citrus",
      palate_zh: "含蓄優雅，礦物感細膩",
      palate_en: "Restrained elegance, fine minerality",
      food_zh: ["山羊芝士", "白肉", "沙拉"],
      food_en: ["Goat cheese", "White meat", "Salads"],
    },
  },
  // 15
  {
    slug: "riesling-dr-loosen-2022",
    name: "Dr. Loosen Riesling 2022",
    type: "white",
    region_zh: "德國 · 摩澤爾 · 白酒",
    region_en: "Germany · Mosel · White",
    grape_variety: "Riesling",
    vintage: 2022,
    tags_zh: ["新手友好", "適合配中菜"],
    tags_en: ["Beginner-friendly", "Pairs with Asian food"],
    description_zh: "德國摩澤爾的經典雷司令，微甜帶酸，像喝礦泉水一樣清新。酒精度低，適合不愛太酒味的人。",
    description_en: "Classic Mosel Riesling — off-dry with racy acidity, fresh as mineral water. Low alcohol, perfect for those who prefer lighter wines.",
    minPrice: 158,
    merchantCount: 5,
    emoji: "🍾",
    tasting_notes: {
      appearance_zh: "淡檸檬色",
      appearance_en: "Pale lemon",
      nose_zh: "青蘋果、蜂蜜、白桃、板岩",
      nose_en: "Green apple, honey, white peach, slate",
      palate_zh: "微甜清爽，酸甜平衡完美",
      palate_en: "Off-dry and fresh, perfect sweet-acid balance",
      food_zh: ["亞洲菜", "辣菜", "甜品"],
      food_en: ["Asian food", "Spicy dishes", "Desserts"],
    },
  },
  // 16
  {
    slug: "gewurztraminer-trimbach-2020",
    name: "Trimbach Gewürztraminer 2020",
    type: "white",
    region_zh: "法國 · 阿爾薩斯 · 白酒",
    region_en: "France · Alsace · White",
    grape_variety: "Gewürztraminer",
    vintage: 2020,
    tags_zh: ["適合配中菜", "果香豐富"],
    tags_en: ["Pairs with Asian food", "Rich fruit"],
    description_zh: "阿爾薩斯的招牌品種，荔枝和玫瑰花瓣香氣撲鼻，配中菜特別好。",
    description_en: "Alsace's signature grape — intoxicating lychee and rose petal aromas. Superb with Chinese cuisine.",
    minPrice: 218,
    merchantCount: 3,
    emoji: "🍾",
    tasting_notes: {
      appearance_zh: "深金黃色",
      appearance_en: "Deep golden",
      nose_zh: "荔枝、玫瑰、生薑、蜂蜜",
      nose_en: "Lychee, rose, ginger, honey",
      palate_zh: "芳香豐富，微甜圓潤",
      palate_en: "Aromatic and rich, off-dry and round",
      food_zh: ["中菜", "咖喱", "泰國菜", "鵝肝"],
      food_en: ["Chinese food", "Curry", "Thai food", "Foie gras"],
    },
  },
  // 17
  {
    slug: "chateau-dereszla-tokaji-5-puttonyos-2017",
    name: "Château Dereszla Tokaji 5 Puttonyos 2017",
    type: "dessert",
    region_zh: "匈牙利 · 托卡伊 · 甜酒",
    region_en: "Hungary · Tokaj · Dessert",
    grape_variety: "Furmint / Hárslevelű",
    vintage: 2017,
    tags_zh: ["果香豐富", "餐後酒"],
    tags_en: ["Rich fruit", "After-dinner wine"],
    description_zh: "匈牙利國寶級甜酒，蜂蜜和杏桃的極致甜蜜，配甜品或單獨品嚐都好。",
    description_en: "Hungary's national treasure — honey and apricot sweetness, wonderful with desserts or on its own.",
    minPrice: 348,
    merchantCount: 3,
    emoji: "🍾",
    tasting_notes: {
      appearance_zh: "深琥珀金色",
      appearance_en: "Deep amber gold",
      nose_zh: "蜂蜜、杏桃、橙皮、焦糖",
      nose_en: "Honey, apricot, orange peel, caramel",
      palate_zh: "甜美而不膩，酸度平衡",
      palate_en: "Sweet but not cloying, balanced acidity",
      food_zh: ["甜品", "藍紋芝士", "水果塔"],
      food_en: ["Desserts", "Blue cheese", "Fruit tarts"],
    },
  },
  // 18
  {
    slug: "chateau-dyquem-2017",
    name: "Château d'Yquem 2017",
    type: "dessert",
    region_zh: "法國 · 波爾多蘇玳 · 甜酒",
    region_en: "France · Bordeaux Sauternes · Dessert",
    grape_variety: "Sémillon / Sauvignon Blanc",
    vintage: 2017,
    tags_zh: ["頂級之選", "值得收藏"],
    tags_en: ["Premium pick", "Worth collecting"],
    description_zh: "世界最頂級的貴腐甜酒，液態黃金般的存在。每一口都是奢華的享受。",
    description_en: "The world's greatest sweet wine — liquid gold. Every sip is pure luxury.",
    minPrice: 3500,
    merchantCount: 2,
    emoji: "🍾",
    badge: "Legendary",
    tasting_notes: {
      appearance_zh: "深金黃色",
      appearance_en: "Deep gold",
      nose_zh: "蜂蜜、杏桃、番紅花、焦糖",
      nose_en: "Honey, apricot, saffron, caramel",
      palate_zh: "極致豐富，完美平衡甜與酸",
      palate_en: "Supremely rich, perfect sweet-acid balance",
      food_zh: ["鵝肝", "藍紋芝士", "法式甜點"],
      food_en: ["Foie gras", "Blue cheese", "French pastry"],
    },
  },
  // 19
  {
    slug: "tignanello-2020",
    name: "Tignanello 2020",
    type: "red",
    region_zh: "意大利 · 托斯卡納 · 紅酒",
    region_en: "Italy · Tuscany · Red",
    grape_variety: "Sangiovese / Cabernet Sauvignon",
    vintage: 2020,
    tags_zh: ["果香豐富", "適合配紅肉"],
    tags_en: ["Rich fruit", "Pairs with red meat"],
    description_zh: "超級托斯卡納的先驅，打破傳統的叛逆之作。強勁而優雅，意大利紅酒的巔峰之一。",
    description_en: "The pioneer of Super Tuscans — a rebel that broke traditions. Powerful yet elegant, among Italy's finest reds.",
    minPrice: 688,
    merchantCount: 4,
    emoji: "🍷",
    tasting_notes: {
      appearance_zh: "深紅寶石色",
      appearance_en: "Deep ruby",
      nose_zh: "黑櫻桃、香料、皮革、可可",
      nose_en: "Black cherry, spices, leather, cocoa",
      palate_zh: "強勁優雅，單寧精緻",
      palate_en: "Powerful yet elegant, refined tannins",
      food_zh: ["燉肉", "牛排", "硬質芝士"],
      food_en: ["Braised meats", "Steak", "Hard cheese"],
    },
  },
  // 20
  {
    slug: "barolo-pio-cesare-2018",
    name: "Pio Cesare Barolo 2018",
    type: "red",
    region_zh: "意大利 · 皮埃蒙特 · 紅酒",
    region_en: "Italy · Piedmont · Red",
    grape_variety: "Nebbiolo",
    vintage: 2018,
    tags_zh: ["值得收藏", "果香豐富"],
    tags_en: ["Worth collecting", "Rich fruit"],
    description_zh: "意大利酒王 Barolo，需要時間來展現魅力。玫瑰花瓣、焦油和松露的複雜香氣。",
    description_en: "The 'King of Italian wines' — Barolo needs time to reveal its charm. Complex aromas of rose petal, tar, and truffle.",
    minPrice: 528,
    merchantCount: 3,
    emoji: "🍷",
    tasting_notes: {
      appearance_zh: "淺石榴紅",
      appearance_en: "Pale garnet",
      nose_zh: "玫瑰、焦油、松露、甘草",
      nose_en: "Rose, tar, truffle, licorice",
      palate_zh: "單寧強勁但優雅，酸度活潑",
      palate_en: "Firm but elegant tannins, lively acidity",
      food_zh: ["松露料理", "燉肉", "陳年芝士"],
      food_en: ["Truffle dishes", "Braised meats", "Aged cheese"],
    },
  },
  // 21
  {
    slug: "rioja-marques-de-riscal-reserva-2018",
    name: "Marqués de Riscal Reserva 2018",
    type: "red",
    region_zh: "西班牙 · 里奧哈 · 紅酒",
    region_en: "Spain · Rioja · Red",
    grape_variety: "Tempranillo",
    vintage: 2018,
    tags_zh: ["性價比高", "百搭"],
    tags_en: ["Great value", "Versatile"],
    description_zh: "西班牙里奧哈的經典陳年紅酒，溫和易飲，帶皮革和香料氣息。性價比極高。",
    description_en: "A classic aged Rioja — smooth and approachable with leather and spice notes. Exceptional value.",
    minPrice: 178,
    merchantCount: 5,
    emoji: "🍷",
    badge: "Best Value",
    tasting_notes: {
      appearance_zh: "中等紅寶石色",
      appearance_en: "Medium ruby",
      nose_zh: "紅莓、皮革、香草、菸草",
      nose_en: "Red berries, leather, vanilla, tobacco",
      palate_zh: "溫和圓潤，橡木味恰到好處",
      palate_en: "Smooth and round, well-judged oak",
      food_zh: ["西班牙火腿", "烤肉", "中等硬度芝士"],
      food_en: ["Jamon", "Grilled meats", "Semi-hard cheese"],
    },
  },
  // 22
  {
    slug: "malbec-catena-zapata-2021",
    name: "Catena Zapata Malbec 2021",
    type: "red",
    region_zh: "阿根廷 · 門多薩 · 紅酒",
    region_en: "Argentina · Mendoza · Red",
    grape_variety: "Malbec",
    vintage: 2021,
    tags_zh: ["適合配紅肉", "果香豐富"],
    tags_en: ["Pairs with red meat", "Rich fruit"],
    description_zh: "阿根廷最好的馬爾貝克之一，紫色花香混合深色水果，口感厚實柔滑。",
    description_en: "One of Argentina's finest Malbecs — purple florals with dark fruit, thick and silky on the palate.",
    minPrice: 298,
    merchantCount: 4,
    emoji: "🍷",
    tasting_notes: {
      appearance_zh: "深紫紅色",
      appearance_en: "Deep purple-red",
      nose_zh: "紫羅蘭、黑莓、李子、可可",
      nose_en: "Violet, blackberry, plum, cocoa",
      palate_zh: "厚實柔滑，單寧甜美",
      palate_en: "Thick and silky, sweet tannins",
      food_zh: ["燒烤", "牛肉", "濃味菜式"],
      food_en: ["BBQ", "Beef", "Rich dishes"],
    },
  },
  // 23
  {
    slug: "pinot-noir-felton-road-2022",
    name: "Felton Road Pinot Noir 2022",
    type: "red",
    region_zh: "紐西蘭 · 中部奧塔哥 · 紅酒",
    region_en: "New Zealand · Central Otago · Red",
    grape_variety: "Pinot Noir",
    vintage: 2022,
    tags_zh: ["果香豐富", "輕盈好入口"],
    tags_en: ["Rich fruit", "Light-bodied"],
    description_zh: "紐西蘭頂級黑皮諾，來自全世界最南端的產區。紅果香氣和絲般質地。",
    description_en: "Top-tier New Zealand Pinot Noir from the world's southernmost wine region. Red fruit and silky texture.",
    minPrice: 438,
    merchantCount: 3,
    emoji: "🍷",
    tasting_notes: {
      appearance_zh: "透亮紅寶石色",
      appearance_en: "Bright ruby",
      nose_zh: "紅櫻桃、覆盆子、香料、泥土",
      nose_en: "Red cherry, raspberry, spice, earth",
      palate_zh: "絲般質地，優雅精緻",
      palate_en: "Silky texture, elegant and refined",
      food_zh: ["鴨肉", "三文魚", "蘑菇料理"],
      food_en: ["Duck", "Salmon", "Mushroom dishes"],
    },
  },
  // 24
  {
    slug: "burgundy-louis-jadot-bourgogne-2021",
    name: "Louis Jadot Bourgogne Pinot Noir 2021",
    type: "red",
    region_zh: "法國 · 勃艮第 · 紅酒",
    region_en: "France · Burgundy · Red",
    grape_variety: "Pinot Noir",
    vintage: 2021,
    tags_zh: ["輕盈好入口", "性價比高"],
    tags_en: ["Light-bodied", "Great value"],
    description_zh: "入門級勃艮第紅酒，讓你用親民價格感受黑皮諾的優雅。紅果香和輕盈酒體。",
    description_en: "Entry-level Burgundy — experience Pinot Noir elegance at an approachable price. Red fruit and light body.",
    minPrice: 198,
    merchantCount: 5,
    emoji: "🍷",
    tasting_notes: {
      appearance_zh: "淺紅寶石色",
      appearance_en: "Light ruby",
      nose_zh: "紅櫻桃、草莓、花香",
      nose_en: "Red cherry, strawberry, floral",
      palate_zh: "輕盈優雅，果味純淨",
      palate_en: "Light and elegant, pure fruit",
      food_zh: ["家禽", "蘑菇", "輕食"],
      food_en: ["Poultry", "Mushrooms", "Light dishes"],
    },
  },
  // 25
  {
    slug: "prosecco-la-marca",
    name: "La Marca Prosecco",
    type: "sparkling",
    region_zh: "意大利 · 威尼托 · 氣泡酒",
    region_en: "Italy · Veneto · Sparkling",
    grape_variety: "Glera",
    tags_zh: ["清爽易飲", "性價比高"],
    tags_en: ["Easy drinking", "Great value"],
    description_zh: "意大利國民氣泡酒，青蘋果和蜂蜜的清新香氣。價格親民，適合隨時開一瓶。",
    description_en: "Italy's favorite sparkling — fresh green apple and honey notes. Affordable enough to pop open anytime.",
    minPrice: 98,
    merchantCount: 6,
    emoji: "🥂",
    badge: "Best Value",
    tasting_notes: {
      appearance_zh: "淺稻草色",
      appearance_en: "Pale straw",
      nose_zh: "青蘋果、蜂蜜、白花",
      nose_en: "Green apple, honey, white flowers",
      palate_zh: "清新活潑，微甜順口",
      palate_en: "Fresh and lively, slightly sweet",
      food_zh: ["開胃菜", "輕食", "早午餐"],
      food_en: ["Appetizers", "Light bites", "Brunch"],
    },
  },
  // 26
  {
    slug: "gruner-veltliner-laurenz-v-2022",
    name: "Laurenz V Grüner Veltliner 2022",
    type: "white",
    region_zh: "奧地利 · 坎普谷 · 白酒",
    region_en: "Austria · Kamptal · White",
    grape_variety: "Grüner Veltliner",
    vintage: 2022,
    tags_zh: ["適合配中菜", "百搭"],
    tags_en: ["Pairs with Asian food", "Versatile"],
    description_zh: "奧地利的國民白葡萄，白胡椒和柑橘的獨特組合。超百搭，特別適合亞洲菜。",
    description_en: "Austria's signature white grape — unique white pepper and citrus combo. Incredibly versatile, especially with Asian food.",
    minPrice: 168,
    merchantCount: 3,
    emoji: "🍾",
    tasting_notes: {
      appearance_zh: "淺黃綠色",
      appearance_en: "Pale yellow-green",
      nose_zh: "白胡椒、柑橘、青草",
      nose_en: "White pepper, citrus, fresh herbs",
      palate_zh: "清爽多汁，有咬口感",
      palate_en: "Fresh and juicy with a savory bite",
      food_zh: ["亞洲菜", "壽司", "沙拉", "雞肉"],
      food_en: ["Asian food", "Sushi", "Salads", "Chicken"],
    },
  },
  // 27
  {
    slug: "cote-du-rhone-guigal-2020",
    name: "E. Guigal Côtes du Rhône 2020",
    type: "red",
    region_zh: "法國 · 隆河谷 · 紅酒",
    region_en: "France · Rhône Valley · Red",
    grape_variety: "Grenache / Syrah / Mourvèdre",
    vintage: 2020,
    tags_zh: ["性價比高", "百搭"],
    tags_en: ["Great value", "Versatile"],
    description_zh: "南法經典混釀，果味奔放，香料氣息豐富。價格親民但品質穩定，日常餐酒首選。",
    description_en: "A classic Southern Rhône blend — exuberant fruit with rich spice notes. Affordable yet consistent — an everyday wine staple.",
    minPrice: 128,
    merchantCount: 6,
    emoji: "🍷",
    tasting_notes: {
      appearance_zh: "深紅寶石色",
      appearance_en: "Deep ruby",
      nose_zh: "紅莓、黑胡椒、百里香",
      nose_en: "Red berries, black pepper, thyme",
      palate_zh: "果味奔放，香料味突出",
      palate_en: "Exuberant fruit, prominent spice",
      food_zh: ["燒烤", "燉菜", "披薩"],
      food_en: ["BBQ", "Stews", "Pizza"],
    },
  },
  // 28
  {
    slug: "chianti-classico-castello-di-ama-2020",
    name: "Castello di Ama Chianti Classico 2020",
    type: "red",
    region_zh: "意大利 · 托斯卡納 · 紅酒",
    region_en: "Italy · Tuscany · Red",
    grape_variety: "Sangiovese",
    vintage: 2020,
    tags_zh: ["百搭", "輕盈好入口"],
    tags_en: ["Versatile", "Light-bodied"],
    description_zh: "經典奇安提，酸度活潑，帶櫻桃和草本香氣。配意大利菜天生一對。",
    description_en: "Classic Chianti with lively acidity, cherry and herbal notes. Born to pair with Italian food.",
    minPrice: 228,
    merchantCount: 4,
    emoji: "🍷",
    tasting_notes: {
      appearance_zh: "明亮紅寶石色",
      appearance_en: "Bright ruby",
      nose_zh: "酸櫻桃、百里香、泥土",
      nose_en: "Sour cherry, thyme, earth",
      palate_zh: "酸度活潑，單寧中等",
      palate_en: "Lively acidity, medium tannins",
      food_zh: ["意大利麵", "披薩", "烤蔬菜"],
      food_en: ["Pasta", "Pizza", "Roasted vegetables"],
    },
  },
  // 29
  {
    slug: "port-tawny-10-year-grahams",
    name: "Graham's 10 Year Tawny Port",
    type: "dessert",
    region_zh: "葡萄牙 · 杜羅河 · 加強酒",
    region_en: "Portugal · Douro · Fortified",
    grape_variety: "Touriga Nacional / Tinta Roriz",
    tags_zh: ["餐後酒", "適合冬天"],
    tags_en: ["After-dinner wine", "Winter wine"],
    description_zh: "陳年茶色波特酒，焦糖、堅果和太妃糖的迷人風味。餐後酒的完美選擇。",
    description_en: "Aged tawny Port with caramel, nut, and toffee flavors. The perfect after-dinner wine.",
    minPrice: 268,
    merchantCount: 3,
    emoji: "🍾",
    tasting_notes: {
      appearance_zh: "琥珀色",
      appearance_en: "Amber",
      nose_zh: "焦糖、核桃、太妃糖、橙皮",
      nose_en: "Caramel, walnut, toffee, orange peel",
      palate_zh: "甜潤柔滑，堅果味悠長",
      palate_en: "Sweet and silky, lingering nutty finish",
      food_zh: ["甜品", "堅果", "巧克力", "芝士"],
      food_en: ["Desserts", "Nuts", "Chocolate", "Cheese"],
    },
  },
  // 30
  {
    slug: "champagne-laurent-perrier-rose",
    name: "Laurent-Perrier Cuvée Rosé",
    type: "sparkling",
    region_zh: "法國 · 香檳區 · 粉紅氣泡酒",
    region_en: "France · Champagne · Rosé Sparkling",
    grape_variety: "Pinot Noir",
    tags_zh: ["送禮首選", "拍照好看"],
    tags_en: ["Great for gifting", "Instagram-worthy"],
    description_zh: "粉紅香檳的標桿之作，全球最受歡迎的粉紅香檳之一。草莓和紅醋栗的優雅氣息。",
    description_en: "The benchmark rosé Champagne — one of the world's most popular. Elegant strawberry and redcurrant notes.",
    minPrice: 488,
    merchantCount: 4,
    emoji: "🥂",
    tasting_notes: {
      appearance_zh: "三文魚粉色",
      appearance_en: "Salmon pink",
      nose_zh: "草莓、紅醋栗、玫瑰",
      nose_en: "Strawberry, redcurrant, rose",
      palate_zh: "細膩活潑，果味優雅",
      palate_en: "Delicate and lively, elegant fruit",
      food_zh: ["海鮮", "壽司", "莓果甜品"],
      food_en: ["Seafood", "Sushi", "Berry desserts"],
    },
  },
  // 31
  {
    slug: "shiraz-penfolds-max-2021",
    name: "Penfolds Max's Shiraz 2021",
    type: "red",
    region_zh: "澳洲 · 南澳 · 紅酒",
    region_en: "Australia · South Australia · Red",
    grape_variety: "Shiraz",
    vintage: 2021,
    tags_zh: ["性價比高", "適合配紅肉"],
    tags_en: ["Great value", "Pairs with red meat"],
    description_zh: "Penfolds 入門級設拉子，黑莓和巧克力的豐富風味。比 Bin 389 更平易近人的選擇。",
    description_en: "Penfolds' entry-level Shiraz — rich blackberry and chocolate flavors. More approachable than Bin 389.",
    minPrice: 198,
    merchantCount: 5,
    emoji: "🍷",
    tasting_notes: {
      appearance_zh: "深紫紅色",
      appearance_en: "Deep purple-red",
      nose_zh: "黑莓、巧克力、黑胡椒",
      nose_en: "Blackberry, chocolate, black pepper",
      palate_zh: "果味豐富，單寧柔順",
      palate_en: "Rich fruit, soft tannins",
      food_zh: ["燒烤", "漢堡", "燉肉"],
      food_en: ["BBQ", "Burgers", "Stews"],
    },
  },
  // 32
  {
    slug: "albarino-martin-codax-2023",
    name: "Martín Códax Albariño 2023",
    type: "white",
    region_zh: "西班牙 · 下海灣 · 白酒",
    region_en: "Spain · Rías Baixas · White",
    grape_variety: "Albariño",
    vintage: 2023,
    tags_zh: ["適合配海鮮", "清爽易飲"],
    tags_en: ["Pairs with seafood", "Easy drinking"],
    description_zh: "西班牙加利西亞的海風白酒，帶明顯的海洋礦物感和柑橘香氣。配海鮮天作之合。",
    description_en: "A sea-breeze white from Galicia — pronounced marine minerality and citrus. A natural match for seafood.",
    minPrice: 148,
    merchantCount: 4,
    emoji: "🍾",
    tasting_notes: {
      appearance_zh: "淺金色帶綠光",
      appearance_en: "Pale gold with green tints",
      nose_zh: "柑橘、白桃、海風、礦物",
      nose_en: "Citrus, white peach, sea breeze, minerals",
      palate_zh: "清爽鹹鮮，礦物感突出",
      palate_en: "Fresh and saline, prominent minerality",
      food_zh: ["海鮮", "壽司", "白灼蝦"],
      food_en: ["Seafood", "Sushi", "Poached prawns"],
    },
  },
];

// ============================================================
// Scenes (4)
// ============================================================

export const scenes: Scene[] = [
  {
    slug: "gift",
    title_zh: "送禮",
    title_en: "Gifting",
    description_zh: "體面又有心意的酒款推薦",
    description_en: "Thoughtful wine gift recommendations",
    emoji: "🎁",
    wineSlugs: [
      "moet-chandon-brut-imperial",
      "dom-perignon-2013",
      "louis-roederer-cristal-2015",
      "champagne-laurent-perrier-rose",
      "opus-one-2019",
      "chateau-dyquem-2017",
    ],
  },
  {
    slug: "dinner",
    title_zh: "聚餐配酒",
    title_en: "Pair with Dinner",
    description_zh: "今晚吃什麼，就配什麼",
    description_en: "Tonight's menu decides the wine",
    emoji: "🍽",
    wineSlugs: [
      "cloudy-bay-sauvignon-blanc-2023",
      "penfolds-bin-389-2021",
      "gewurztraminer-trimbach-2020",
      "rioja-marques-de-riscal-reserva-2018",
      "chianti-classico-castello-di-ama-2020",
      "cote-du-rhone-guigal-2020",
    ],
  },
  {
    slug: "everyday",
    title_zh: "日常小酌",
    title_en: "Everyday Sips",
    description_zh: "下班後的小確幸",
    description_en: "After-work happiness in a glass",
    emoji: "🍷",
    wineSlugs: [
      "marlborough-villa-maria-sauvignon-blanc-2023",
      "prosecco-la-marca",
      "santa-margherita-pinot-grigio",
      "cote-du-rhone-guigal-2020",
      "shiraz-penfolds-max-2021",
      "burgundy-louis-jadot-bourgogne-2021",
    ],
  },
  {
    slug: "explore",
    title_zh: "探索新世界",
    title_en: "Explore New Wines",
    description_zh: "跳出舒適圈，試試不一樣的",
    description_en: "Step outside your comfort zone",
    emoji: "🌍",
    wineSlugs: [
      "gruner-veltliner-laurenz-v-2022",
      "riesling-dr-loosen-2022",
      "chateau-dereszla-tokaji-5-puttonyos-2017",
      "albarino-martin-codax-2023",
      "masi-costasera-amarone-2018",
      "barolo-pio-cesare-2018",
    ],
  },
];

// ============================================================
// Prices (per wine slug)
// ============================================================

export const winePrices: Record<string, MerchantPrice[]> = {
  "cloudy-bay-sauvignon-blanc-2023": [
    { merchant: "Watson's Wine", merchantSlug: "watsons-wine", price: 138, isBest: true },
    { merchant: "Wine & Co", merchantSlug: "wine-and-co", price: 155, isBest: false },
    { merchant: "CellarDoor", merchantSlug: "cellardoor", price: 168, isBest: false },
    { merchant: "VinHK", merchantSlug: "vinhk", price: 172, isBest: false },
    { merchant: "Grape HK", merchantSlug: "grape-hk", price: 185, isBest: false },
    { merchant: "BottleShop", merchantSlug: "bottleshop", price: 198, isBest: false },
  ],
  "penfolds-bin-389-2021": [
    { merchant: "Grape HK", merchantSlug: "grape-hk", price: 328, isBest: true },
    { merchant: "Watson's Wine", merchantSlug: "watsons-wine", price: 348, isBest: false },
    { merchant: "CellarDoor", merchantSlug: "cellardoor", price: 358, isBest: false },
    { merchant: "Wine & Co", merchantSlug: "wine-and-co", price: 368, isBest: false },
  ],
  "moet-chandon-brut-imperial": [
    { merchant: "Watson's Wine", merchantSlug: "watsons-wine", price: 268, isBest: true },
    { merchant: "Wine & Co", merchantSlug: "wine-and-co", price: 288, isBest: false },
    { merchant: "Grape HK", merchantSlug: "grape-hk", price: 298, isBest: false },
  ],
  "whispering-angel-rose-2023": [
    { merchant: "CellarDoor", merchantSlug: "cellardoor", price: 198, isBest: true },
    { merchant: "Watson's Wine", merchantSlug: "watsons-wine", price: 218, isBest: false },
    { merchant: "BottleShop", merchantSlug: "bottleshop", price: 228, isBest: false },
  ],
  "masi-costasera-amarone-2018": [
    { merchant: "Wine & Co", merchantSlug: "wine-and-co", price: 388, isBest: true },
    { merchant: "VinHK", merchantSlug: "vinhk", price: 408, isBest: false },
    { merchant: "Watson's Wine", merchantSlug: "watsons-wine", price: 418, isBest: false },
  ],
  "santa-margherita-pinot-grigio": [
    { merchant: "Grape HK", merchantSlug: "grape-hk", price: 168, isBest: true },
    { merchant: "CellarDoor", merchantSlug: "cellardoor", price: 178, isBest: false },
    { merchant: "Watson's Wine", merchantSlug: "watsons-wine", price: 188, isBest: false },
  ],
};

// Keep backward compatibility
export const cloudyBayPrices = winePrices["cloudy-bay-sauvignon-blanc-2023"];
